name: Feature Request
description: Suggest a new feature for Win-Debloat7
labels: [enhancement]
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Bloatware Removal
        - Privacy Tweak
        - Performance Tweak
        - GUI Improvement
        - New Software Package
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like it to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
    validations:
      required: false
